name: GatorGrader

on:
  push:
    branches: [main]

jobs: 
  grade:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with: 
        fetch-depth: '0'
    - name: Setup Maven
      if: always()
      run: |
        sudo apt-get install default-jre
        sudo apt-get install default-jdk
        sudo apt-get install maven
    - name: Run jUnit tests
      if: always()
      run: |
        mvn test
    - name: Setup Python
      if: always()
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Set up grading environment
      run: |
        sudo apt-get update
        sudo python -m pip install --upgrade pip
        sudo python -m pip install gatorgrade --ignore-installed PyYAML
    - name: Grade repository
      run: |
        gatorgrade --config gatorgrade.yml --report file json gatorgrade_summary.json
      if: always()
      env:   
        PIPENV_VENV_IN_PROJECT: 1
        PIPENV_IGNORE_VIRTUALENVS: 1
    - name: Create Wizard report
      id: wizard
      uses: term-world/wizard@main
      with:
        grader-report: 'gatorgrade_summary.json'
      if: always()
    env:
      GITHUB_TOKEN: ${{ secrets.ARBORIST }}
