name: GatorGrader

on:
  push:
    branches: [main]

jobs: 
  grade:
    runs-on: ubuntu-latest
    steps:
    - name: Arborist protection
      id: arborist
      uses: term-world/arborist@v0.1.5
      with:
        branches: '["main", "feedback"]'
        min-approvals: 1
        enforce-admins: true
      if: always()
    env:
      GITHUB_TOKEN: ${{ secrets.WIZARD }}
